// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGFePsEwdQeRo-5RtTo6gYXEGtMpfDuM',
    appId: '1:460123660108:web:1d2d9907d9d83e1ed079e9',
    messagingSenderId: '460123660108',
    projectId: 'reddit-clone-riverpod-app',
    authDomain: 'reddit-clone-riverpod-app.firebaseapp.com',
    storageBucket: 'reddit-clone-riverpod-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZiDVWapwiOE78OADLBha0NmAW1FCvIUg',
    appId: '1:460123660108:android:9b81ca1629b2907fd079e9',
    messagingSenderId: '460123660108',
    projectId: 'reddit-clone-riverpod-app',
    storageBucket: 'reddit-clone-riverpod-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiBsrxQgVuOlhLkxYQ914LT6nxTB2S9Ag',
    appId: '1:460123660108:ios:25688d90bc2a4d6bd079e9',
    messagingSenderId: '460123660108',
    projectId: 'reddit-clone-riverpod-app',
    storageBucket: 'reddit-clone-riverpod-app.appspot.com',
    iosClientId: '460123660108-abibh7afg80pv0eugrsuk03pjik6hbe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiBsrxQgVuOlhLkxYQ914LT6nxTB2S9Ag',
    appId: '1:460123660108:ios:25688d90bc2a4d6bd079e9',
    messagingSenderId: '460123660108',
    projectId: 'reddit-clone-riverpod-app',
    storageBucket: 'reddit-clone-riverpod-app.appspot.com',
    iosClientId: '460123660108-abibh7afg80pv0eugrsuk03pjik6hbe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneRiverpod',
  );
}
